Sort reference origins
hashicorp/hcl-lang pull request #124
Opened 2022-07-27 16:46 UTC by dbanck

After running into this a couple of times [recently](https://github.com/hashicorp/hcl-lang/runs/7543556000?check_suite_focus=true), this PR now sorts the reference origins by path, filename and range.

Closes https://github.com/hashicorp/hcl-lang/issues/101

2022-07-27 16:48 UTC, radeksimko approved these changes
Thanks! :shipit:

2022-07-27 16:49 UTC, radeksimko requested changes
Actually the tests still seem to be failing

2022-07-27 18:19 UTC, dbanck commented
I shouldn't copy and extend sort functions without checking them first.

It should work now
![CleanShot 2022-07-27 at 20 17 54](https://user-images.githubusercontent.com/45985/181344031-721e6142-de3d-4112-8258-e1219b2e4920.png)

2022-07-28 06:24 UTC, radeksimko approved these changes
Thanks for the update

2022-07-28 07:44 UTC, merged