WIP: Support for nested expressions
hashicorp/hcl-lang pull request #177
Opened 2022-12-23 16:28 UTC by radeksimko

Closes https://github.com/hashicorp/terraform-ls/issues/496

2023-01-08 18:34 UTC, dbanck requested changes
Great work! I believe the changes will lead to a much more readable and easier extendable codebase. I've just found two minor things.

Regarding your questions:
> Should decoder.Expression.ReferenceOrigins() accept context as the first argument, like the other methods?

I'm in favor as it will unify the interface, and we might need it anyway.

> Should we also use that context to pass through "allowSelfRefs" somehow?

Maybe. But I would leave this open until we get to the implementation.

> Should decoder.PathDecoder.CollectReferenceOrigins() also accept context, like other similar methods?

I'm against it for now as I couldn't find a good use-case yet.

> Should decoder.Expression.ReferenceTargets() accept context as the first argument, like the other methods?

I'm in favor as it will unify the interface, and we might need it anyway.

> Should decoder.PathDecoder.CollectReferenceTargets() also accept context, like other similar methods?

I'm against it for now as I couldn't find a good use-case yet.

> Should we be updating tests, or copying them - i.e. should the old logic remain covered by tests in the meantime?

I'm in favor of copying tests and removing the old tests together with the old implementation. That should ensure we keep everything unbroken.

2023-01-09 09:30 UTC, radeksimko commented on decoder/expression_candidates.go
> +		if con, ok := aSchema.Constraint.(schema.Conformable); ok && con.Conforms(cty.String) {
True, good catch!

2023-01-09 09:33 UTC, radeksimko commented on decoder/reference_origins.go
> -func (d *PathDecoder) referenceOriginAtPos(body *hclsyntax.Body, bodySchema *schema.BodySchema, pos hcl.Pos) (*reference.Origin, error) {
Good catch! Will do.

2023-01-09 19:47 UTC, radeksimko commented
I believe I have addressed all concerns + I also decided to change the `Conformable` interface to `Comparable`, with the assumption that we _will_ reuse it eventually for https://github.com/hashicorp/terraform-ls/issues/583 - I can not see why hooks shouldn't take advantage of that potentially more loose interpretation of type compatibility.

PTAL

2023-01-10 10:59 UTC, dbanck approved these changes
Thanks! LGTM 👍

2023-01-10 11:02 UTC, merged