fix nil expr panics
hashicorp/hcl-lang pull request #376
Opened 2024-02-20 10:47 UTC by ansgarm

- fix: handle nil expr for hover
- fix: handle nil expr for reference origins and semantic tokens
- fix: handle nil expr for reference targets

2024-02-22 10:56 UTC, ansgarm commented on go.mod
> +	github.com/hashicorp/hcl/v2 v2.19.2-0.20240209134327-1e1a6b858a91
blocked on a new release of `hashicorp/hcl`

2024-02-28 11:09 UTC, dbanck requested changes
LGTM! Minor suggestion to suppress completion

2024-02-28 12:43 UTC, ansgarm commented on decoder/candidates.go
> +		if attr.Expr != nil && d.isPosInsideAttrExpr(attr, pos) {
Makes sense!

2024-02-29 10:33 UTC, dbanck approved these changes

2024-02-29 10:33 UTC, merged